### ISSUE TITLE
Reference for error numbers

### ISSUE THREAD

**Issue by sassanh** [python-sdbus/python-sdbus-networkmanager#60]
Hi, thanks for this helpful package. I'm getting this error when instantiating async `NetworkManager`

```
1703350642.967676 [ERROR] File: src/sdbus/sd_bus_internals_bus.c Line: 337. sd_bus_call_async(self->sd_bus_ref, &new_slot_object->slo
t_ref, call_message->message_ref, SdBus_async_callback, new_future, (uint64_t)0) in function SdBus_call_async returned error number: 
107
```

I don't understand what's wrong, it would be helpful if I knew what does error number 107 mean.

**Comment by sassanh** [comment]
I guess it happens when an sdbus connection is not used for a while and then it is reused. But still I think it would be helpful if we know the meaning of the error numbers, sometimes I get 123 for example.

**Comment by sassanh** [comment]
I noticed these are probably linux error codes documented [here](https://chromium.googlesource.com/chromiumos/docs/+/master/constants/errnos.md) for example.

**Comment by igo95862** [comment]
Hello @sassanh 

> I noticed these are probably linux error codes documented here for example.

Indeed. There is also the `errno` module in Python's standard library: https://docs.python.org/3/library/errno.html

You should also check the sd-bus manual pages because they have the error codes explanation. For example, this is the page for the `sd_bus_call_async` function:

https://man.archlinux.org/man/sd_bus_call_async.3.en#RETURN_VALUE

```
-ENOTCONN
The input parameter bus is NULL or the bus is not connected. 
```

I originally tried using the `strerrorname_np` function to convert error codes to the names but it turned out to be very buggy and also only supported on glibc.
